### ISSUE TITLE
Display summaries on main blog page

### ISSUE THREAD

**Issue by dmcassel** [marklogic/RunDMC#349]
When you look at the blog page, you see the entire text for the last three blog posts. It's difficult to scan the list and see what the recent content is, especially when one or two of those posts are long. 

For the main blog page, display a summary of each post's text instead of the whole thing. Limit to the first 200 words or so. Note that this will take some care to make sure we have valid XHTML.

**Comment by dmcassel** [comment]
@mariannemyers is taking this one

**Comment by dmcassel** [comment]
Blog posts have a "short description" that can be used as an abstract. When that's available, display that.

**Comment by mariannemyers** [comment]
Rather than limiting to 200 words when a short description is not available, would limiting to the first 1000 character be acceptable?  This looks fairly nice on the page at different browser sizes too.

I'll also be adding an ellipse to indicate more content, which will be a clickable link to the post.
