### ISSUE TITLE
search is not highlighting text on search hits

### ISSUE THREAD

**Issue by dsokolsky** [marklogic/RunDMC#358]
It looks like search results are not getting highlighted on the page after clicking on a result.  For example, if search for "lexicon", then click on the first result, the word lexicon is not highlighted on the displayed page.

I think it used to be...  At any rate, it probably should be.

**Comment by mblakele** [comment]
This is working on the production site, right? I think the problem is in `src/config/server-urls.xml` rather than in code.

Technically setting a cookie on an IP address or localhost is not supposed to work: http://tools.ietf.org/html/rfc6265 section 5.1.3 describes the rules. But in practice it seems to work if I change `127.0.0.1` to `localhost`, with firefox 34. Or it's more robust to create a host entry like `local.marklogic.com` for dev environments, and use the same name in `src/config/server-urls.xml`.

**Comment by dsokolsky** [comment]
Ah, this is some of the wierdness of this app....  I'm not sure what the right thing to do is.  It does work it production, and it also works in stage.  Just not on pubs.  I think there is some apache magic that resolves it on stage and prod.  @dmcassel : do you know how this works?  I wonder if we even need this anymore?  I guess we muct since this stuff uses it...

**Comment by mblakele** [comment]
What if we move the highlight query out of the cookie and use a request param instead? That would avoid the need to immediately unset the cookie, although it would mean some links and bookmarks might include the extra param. That would also make the `server-urls` config less important for non-production deployments: it'd only be used for user login persistence, I think.

**Comment by dsokolsky** [comment]
That makes sense to me.  Do you see a problem with that @dmcassel ?

**Comment by dmcassel** [comment]
src/config/server-urls.xml is being used to generate the navigation links. Changing the cookie-domain from 127.0.0.1 to localhost works for Firefox, but not Chrome.

**Comment by dsokolsky** [comment]
I think we should move this to a request parameter.  Dave, if you disagree let us know.

**Comment by mblakele** [comment]
To try and clarify, the idea behind moving highlight state from a cookie to a request param isn't to remove `server-urls.xml`. We'll still use that file for other purposes like nav links. We'll still use its `cookie-domain` for user login state, too, so the problems with `localhost` or `127.0.0.1` will still exist for user login state. But I'm assuming that we only care about user login state on `developer.marklogic.com` and `stage-developer.marklogic.com`. The `cookie-domain` problem doesn't exist there because those are cookie-valid hostnames. It's only a problem in development and internal systems where IP addresses or short hostnames are used.

**Comment by dmcassel** [comment]
I'm on board with moving to a request param.

On Wed, Jan 7, 2015 at 1:54 PM, Michael Blakeley <notifications@github.com>
wrote:

> To try and clarify, the idea behind moving highlight state from a cookie
> to a request param isn't to remove server-urls.xml. We'll still use that
> file for other purposes like nav links. We'll still use its cookie-domain
> for user login state, too, so the problems with localhost or 127.0.0.1
> will still exist for user login state. But I'm assuming that we only care
> about user login state on developer.marklogic.com and
> stage-developer.marklogic.com. The cookie-domain problem doesn't exist
> there because those are cookie-valid hostnames. It's only a problem in
> development and internal systems where IP addresses or short hostnames are
> used.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/marklogic/RunDMC/issues/358#issuecomment-69071179>.
>



-- 
http://blog.davidcassel.net
http://www.linkedin.com/in/davidcassel

**Comment by dsokolsky** [comment]
This is fixed, although I opened #368 for a similar (but different) issue.
