### ISSUE TITLE
search highlighting not highlighting function name

### ISSUE THREAD

**Issue by dsokolsky** [marklogic/RunDMC#368]
If you go to the search result page for something like xdmp:document-insert, it does not highlight the text in the signature. For example:

``/8.0/xdmp:document-insert?hq=xdmp%3Adocument-insert``

The xdmp:document-insert in the function signature is not highlighted, but the other instances on the page are.

**Comment by mblakele** [comment]
Production doesn't seem to do this either, using the older code. Did it ever highlight the signature?

I think `u:highlight-doc` does highlights the signature, but then the `mode="function-signature"` transforms discard the highlighting. That may be difficult to handle without calling `cts:highlight` a second time.

**Comment by dsokolsky** [comment]
I don't think it ever did highlight the signature.

Maybe ``mode="function-signature"`` can be called before ``u:highlight-doc``.  If it is too hard, we can live with it.  I just noticed while I was testing #358, but figured it was totally unrelated to that so filed this bug.

**Comment by mblakele** [comment]
Yes, that might work. I'll look into it.

**Comment by mblakele** [comment]
I'm not thrilled with this solution: it opens up the door to extra highlight calls in an unbounded number of places, which could get ugly.

Another approach would be to highlight everything in `ml:page-content` after apply that transform. But that would include things like the `h1` heading and the `JavaScript: xdmp.document-insert` link, which might not be desirable. I could try to control that in the `cts:highlight` expression, but as you know the `$cts:node` can be at whatever level the query term matched at. So that isn't always easy to figure out.

**Comment by dsokolsky** [comment]
Fixed.
