### ISSUE TITLE
scrolling issues on iOS devices

### ISSUE THREAD

**Issue by dsokolsky** [marklogic/RunDMC#402]
This was reported by Will on support.  I have reproed it on the "procedures" chapter of the install guide on the live site and on the staging site, which is running the latest code.  I am using an iphone 5.  When it gets to the images on that page, it seems to go a little past there and then scroll back to the beginning part of the images.

Here is from Will:

The docs.marklogic.com content panel scroll bar is broken on iOS. It won't allow you to scroll to the bottom of documents. Before I get to the bottom of the document some event interrupts and jumps back to an arbitrary point in the middle of the document. If I select a link from the TOC panel that links to an anchor at the bottom of the page, it goes there, but it immediately jumps back to said arbitrary mid page position.

**Comment by mblakele** [comment]
So far I can't reproduce this with iOS 8.1.2 on an iPad4. If I load `/guide/installation/procedures` I can scroll to the bottom and see the footer with the copyright and "powered by" notices. Scrolling feels very slow, though.

I can reproduce it easily on an iPhone6 with iOS 8.1.3. There's also something weird on the iPhone where the location bar disappears and I can't figure out how to get it back. Because of these problems I suspect something's looking at screen width and changing behavior based on that. It may have something to do with bootstrap.

**Comment by mblakele** [comment]
Chrome's tools tell me that the slow scrolling is probably caused by repainting: at least three separate bits inside `#page_content` need repainting on scroll.

Oddly that may also cause the reported problem. At first I thought it must be a mouseup event, but disabling javascript entirely doesn't fix it. However disabling `apidoc.css` does. So it may be a bug in iOS Safari around the repainting regions. It's going to be time-consuming to find the rule(s) in `apidoc.css` that trigger the problem. So far I can only reproduce it on my phone and in the xcode iphone simulator.

**Comment by dsokolsky** [comment]
It seems to me this is a newish problem, although I cannot say for sure.  Maybe look at changes in the last 6 months?

**Comment by mblakele** [comment]
Not sure how new it is, but it's the same kind of CSS problem we've been dealing with for some time. It just keeps moving around. In dcb67d9 I rebuilt the basic CSS from scratch, and I think it will be more robust.

**Comment by dsokolsky** [comment]
It looks good, although I have not yet had a chance to try it on a phone.

One issue I notice, however, is that the scoll bar in the toc is about 2/3 hidden by the right-hand gey vertical bar running up and down the toc.  I see this on chome and firefox.  Also, the splitter no longer lets you make the toc wider.  I am going to assign this back to you to check that out.

**Comment by dsokolsky** [comment]
The slider definitely does work, it just has a very thin margin to select.  It works a lot better than it did before once you get it selected though.  I sent you a screenshot of the grey bar that is in the way for me.

**Comment by dsokolsky** [comment]
Calling this done.  Thanks Mike.
