### ISSUE TITLE
highlight widget doesn't work properly on main site

### ISSUE THREAD

**Issue by mblakele** [marklogic/RunDMC#440]
This is due to bad logic in page initialization: https://github.com/marklogic/RunDMC/blob/dcb67d9fd5796e5364049441ca6e5afee66f9801/src/js/rundmc_init.js#L39 returns if there's no version widget, so the highlight widget init code never runs. I'll reorganize it so that each component has its own init function.

**Comment by mblakele** [comment]
@dmcassel The fix is in docapp but you should be able to cherry-pick this into master if you like. I wouldn't merge docapp into master right now: too many other changes.

**Comment by kcoleman-marklogic** [comment]
Is this still pending for DMC? You don't say how they're not working properly, but it can be pretty intrusive on DMC right now because of positioning. For example, I went to DMC and searched for "geospatial", then chose the Tutorials facet and eventually ended up here:

http://developer.marklogic.com/learn/maps-for-appbuilder-apps?hq=geospatial

Instead of being off in the upper right corner, the widget is nearish the middle. Also, this page doesn't have pinned header, so, as you scroll, the widget just floats around a couple inches below the top of the content. It is very intrusive. See below.

![highlight-widget](https://cloud.githubusercontent.com/assets/1951367/6469771/00973ad8-c194-11e4-8a19-736a0a5de708.jpg)

**Comment by mblakele** [comment]
No, that wasn't part of 61d911d. This was a JavaScript-only change. @dmcassel I don't think it's been deployed yet. That means the close `X` doesn't work, so there's no way to get rid of the highlight widget. Also the history replacement doesn't happen, so the final page URL still has `hq` in it.

Getting back to this layout problem, I think you should open a new issue for it. It looks like an easy CSS change that either Dave or I could do.

**Comment by kcoleman-marklogic** [comment]
Filed #458 about the layout problem.

**Comment by dsokolsky** [comment]
This looks to be fixed now with the latest stuff (deployed as part of 7.0-5).   I'm closing this.  Feel free to reopen if I am wrong (or file another bug if it is a different problem).
