### ISSUE TITLE
Provide user-copiable links to glossary entries

### ISSUE THREAD

**Issue by dmcassel** [marklogic/RunDMC#446]
When looking at the glossary, make it so that a user can click something and get a link to that particular entry. Such links can be constructed manually, so this is a matter of making them accessible through the UI. 

Example: here's the link for facet: http://docs.marklogic.com/guide/copyright/glossary#id_pgfId-920128

**Comment by dsokolsky** [comment]
I don't want to do this yet because this has the potential to cause more issues than it solves (gratuitous links).  It requires a bunch of thought and design I think.

**Comment by dmcassel** [comment]
Cool. Not a high priority thing, but when I'm writing blog posts and other stuff, I think it would be useful to link to terms.

**Comment by dsokolsky** [comment]
I think I misunderstood what you are asking for.  I had originally thought you wanted it to automatically link words to the glossary terms, but I think you are just asking for clean URLs to the terms.

Clean URLs is something we had thought of doing.  At first, we had thought about making it like the links to the messages, and making each term its own page.  But the reason we are not doing that is that we think the glossary is a bit of a different beast than the messages.  For the messages, you really only want to look at one thing.  But for the glossary, there is some value of randomly browsing it, so that if you look up one word you can get to another word.

Now what I think we can do is to make each term a link that puts in the URL with the proper anchor in the URL bar.  That might be possible.

**Comment by dmcassel** [comment]
Yup, that's all I'm suggesting. If I do a blog post that mentions collections, I could manually (but simply) get a link to the "collection" entry in the glossary and add that to the post.

**Comment by dsokolsky** [comment]
I think the way to do this is just to make each glossary item a link with the href to itself, the same way we do for chapter titles.

Mike can you make this so?  Do you need us to make those headings a different style (so the XML has a different name) in order to do that?  If so let me know and we can do that.

**Comment by mblakele** [comment]
Seems like a clean path would include the glossary term, since terms are unique: `/guide/copyright/glossaryfacet` rather than `/guide/copyright/glossary/id_pgfId-920128`. We could probably make `/glossary/facet` work too, perhaps with a redirect.

It would be nice if the XML included unambiguous markup for each term and definition, but I think I can infer it during setup.

**Comment by mblakele** [comment]
Reading this again I think I misunderstood, and Danny was proposing `/guide/copyright/glossary#facet`. That's easier, so I'll do that first and we can discuss redirects as needed.

**Comment by mblakele** [comment]
You should be able to cherry-pick 30ad14e if you don't want to take all the changes currently in docapp. It's fairly self-contained, and should only require `deploy_docs --ml.build-actions=setup-guides`.

**Comment by dsokolsky** [comment]
This is working, but it is not quite user copyable.  You have to manually add #term to the end.

Is it hard to turn each heading for the gloss terms into a link to that url?  Then you can click on it and copy the url.

**Comment by dsokolsky** [comment]
I am fine to take all of the changes in docapp.  Can you please to one more merge to master?

**Comment by dsokolsky** [comment]
It looks like it is not working in all cases.  For example:

/guide/copyright/glossary#Asynchronous Replication

I think maybe because of the spaces.

**Comment by mblakele** [comment]
I think the link is fine. The problem appears to be in the new JavaScript code that scrolls on popstate, from #379.

**Comment by mblakele** [comment]
Spaces, and parens too.

**Comment by dsokolsky** [comment]
This looks good.  It is currently staged and should be live by the end of the day.  Thanks all.
