### ISSUE TITLE
jsearch methods are missing params in func signatures

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/RunDMC#562]
IDK when this started happening. It's only broken on pubs. All the jsearch related methods are showing up like this:
```
DocumentsSearch.where as DocumentsSearch
```
Instead of, say, like this:
```
DocumentsSearch.where(
   $queries as cts.query
) as DocumentsSearch
```
It's broken in all ML version flavors, and it's broken for all the functions in jsearch.xml. Gordon's optics stuff has the same problem, but since I think he's been copying what I did for jsearch, that's not too surprising.

I'm not seeing any problems with the JS apidoc derived from the XQuery modules, so perhaps some special casing for jsearch in the app got broken. 

Or perhaps I need to specify something explictly in that module that was previously working by accident. For example, I only have a class=javascript attr on the apidoc:module because everything in the module is JS-only. Maybe that's not good enough any longer?

**Comment by dsokolsky** [comment]
This appears to be something that has broken in the last day or two.  I am pretty sure it is a problem with our content, not with the RunDMC code, but I am not positive at this point.

**Comment by dsokolsky** [comment]
I think this is because the code I had in there does not run the same on 8 as it does on 7, and my local env I was testing as well as the production site are on 7, but pubs is on 8.  This is the change I made:

https://github.com/marklogic/RunDMC/commit/b1fabcecfadfdbd3c70b7638d2ef6193df3919d2

I think it did not work because of some kind of xslt standards thing on a boolean test, but I am not sure.

@kcoleman-marklogic and @gfurbush , please let me know if it seems to be working right on pubs tomorrow.

**Comment by dsokolsky** [comment]
BTW, this does not need a new build to test out, as this code is entirely display code.  It looks to me like it is working.

**Comment by kcoleman-marklogic** [comment]
Looks good to me. I took a quick look at the optic funcs, too, and they also seem fine now. Thank you!

That's a worrisome little behavior change (in the XSLT). Makes one wonder what other sneaky little problems are lurking in the output.

**Comment by dsokolsky** [comment]
For posterity, this is not really a difference in xslt behavior.  It is because the default attributes values are serializing differently in 8 than in 7. This is because the schema in 8.0 includes is-property with a default value of false, and the is-property attr does not exist in the schema in 7.0.  The code change I made looks for the value of true, which only shows up when the "function"  or "method" is a property.  So the mystery is solved.
