### ISSUE TITLE
Docs link in nav from search page returning 404

### ISSUE THREAD

**Issue by dsokolsky** [marklogic/RunDMC#563]
Thanks @popzip for noticing this.

When I search on public facing docs site, and then try to click back to docs home page using the hyperlink ‘Docs’ in top left, I got an error.  I cannot reproduce using pubs.marklogic.com so I’m not sure if this is something that’s been fixed or if it’s an error that happens when docs are pushed live. Let me know what you think.

From this search result: http://developer.marklogic.com/search?q=cat%3Aguide%2Fapp-dev%20%28management%20rest%20api%29&api=true&v=8.0
Click ‘Docs’ in top left'

**Comment by kcoleman-marklogic** [comment]
Did this ever work? I suspect pubs is not a good testbed for it because pubs reflects a docs-only world view.

I think the problem is that the search results page on live is rooted at developer.marklogic.com (as it has to be since it encompasses the whole site). That "Docs" link is an href to /8.0, so of course it ends up trying to go to developer.marklogic.com/8.0 instead of docs.marklogic.com/8.0. 

Or do you guys have some redirect magic that is supposed to make that work?

**Comment by dsokolsky** [comment]
I doubt it ever worked.  Yes @kcoleman-marklogic, that is the reason.  I think I know how to fix it.

**Comment by dsokolsky** [comment]
OK, I think this is fixed now.  Hopefully I didn't break anything else....I think it is OK.  I pushed it live.  At first I was going to change the link, but I instead made a redirect of /8.0 (or any version) to /8.0 on docs.  What this means is that we cannot have /8.0 (or any version) on developer, but I think that is OK.  @dmcassel, @paxtonhare, keep that in mind.

**Comment by dsokolsky** [comment]
I made the regex a little more restrictive because it previously matched all rooted (starting with /version) docs pages.  Now it only match /version (/8.0, /7.0, for example).
